---
- name: install docker with ansible
  hosts: tomcat
  become: true
  remote_user: ansadmin
  tasks:
          
          - name: update the system
            apt:
                    update_cache: yes
                    force_apt_get: true
      
   
          - name: install tools
            apt: 
              name: 
                 - ca-certificates
                 - curl
                 - gnupg
                 - lsb-release

          - name: create directory for docker key
            file:
              path: /etc/apt/keyrings
              state: directory
              owner: ansadmin
              group: ansadmin

            
          - name: get gpg key 
            get_url:
                         url: https://download.docker.com/linux/ubuntu/gpg
                         dest: /etc/apt/keyrings/docker.gpg
                               
          - name: add docker key 
            apt_key:
                    file: /etc/apt/keyrings/docker.gpg
                    state: present


          - name: set up repository
            shell: echo \
                           "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable" | sudo  tee /etc/apt/sources.list.d/docker.list > /dev/null
                     
                

             
          - name: update the apt package
            apt: 
                update_cache: yes
                force_apt_get: true
          
          - name: install docker 
            apt:
                    name:
                            - docker-ce
                            - docker-ce-cli
                            - containerd.io
                            - docker-compose-plugin
          - name: add user to docker group
            user:
                    name: ansadmin
                    append: yes
                    groups: docker
            become: true

